"""empty message

Revision ID: 82bc1489986e
Revises: cfab5f83683a
Create Date: 2024-10-19 19:46:52.346716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82bc1489986e'
down_revision = 'cfab5f83683a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Se elimina la columna 'occupation' porque se ha reemplazado por una categoría más específica en otra tabla
    # Se añaden columnas nuevas para capturar más detalles específicos de los personajes
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mass', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('hair_color', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('skin_color', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('eyes_color', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('birth_year', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('homeworld', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('species', sa.String(length=80), nullable=True))
        batch_op.drop_column('occupation')
        batch_op.drop_column('address')
        batch_op.drop_column('age')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rotation_period', sa.Float(), nullable=True))  # Cambiado a Float
        batch_op.add_column(sa.Column('orbital_period', sa.Float(), nullable=True))  # Cambiado a Float
        batch_op.add_column(sa.Column('diameter', sa.Integer(), nullable=True))  # Cambiado a Integer
        batch_op.add_column(sa.Column('climate', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('gravity', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('terrain', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('population', sa.Integer(), nullable=True))  # Cambiado a Integer


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inhabitant_height', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('galaxy', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('type_of_inhabitant', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_column('population')
        batch_op.drop_column('terrain')
        batch_op.drop_column('gravity')
        batch_op.drop_column('climate')
        batch_op.drop_column('diameter')
        batch_op.drop_column('orbital_period')
        batch_op.drop_column('rotation_period')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('age', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('occupation', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('species')
        batch_op.drop_column('homeworld')
        batch_op.drop_column('gender')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('eyes_color')
        batch_op.drop_column('skin_color')
        batch_op.drop_column('hair_color')
        batch_op.drop_column('mass')
        batch_op.drop_column('height')

    # ### end Alembic commands ###
